apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: sk052-stock-api
  namespace: skala-practice
spec:
  ingressClassName: public-nginx
  rules:
    - host: sk052-stock-api.skala25a.project.skala-ai.com
      http:
        paths:
          - backend:
              service:
                name: sk052-stock-api
                port:
                  number: 8080
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: sk052-stock-api
                port:
                  number: 8081
            path: /actuator
            pathType: Prefix
          - backend:
              service:
                name: sk052-stock-api
                port:
                  number: 8080
            path: /swagger
            pathType: Prefix
          - backend:
              service:
                name: sk052-stock-ui
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "sk052-stock-api.skala25a.project.skala-ai.com"
      secretName: skala25-project-tls-cert
